name: CustomTree
main: com.robinmc.customtree.Main
version: 1.0.0
author: RobinMC
description: Generates all kinds of custom trees
depend: [WorldEdit]
website: http://robinmc.com/

commands:
  customtree:
    usage: |
      /customtree list - Displays all possible tree types
      /customtree <type> - Set tree type
    description: Main command for the CustomTree plugin.  